## Basic Configuration
baseurl = "https://jim091418.github.io/"
languageCode = "zh"

title = "Jim Tang Blog"
theme = "triple-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Jim Tang"
    title = "Title12344"
    description = "努力奮發向上的鹹魚"
    authorimage = "/img/Q_shiba.png"
    #dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    #logoimage = "/img/hugo.png"
    copyright = "derme302"
    since = 2023
    license = "jimtang"
    # licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

[params.giscus]
    # repo = "author/repo"
    # repoID = "<id>"
    # category = "Announcements"
    # categoryID = "<id>"
    mapping = "pathname"
    strict = "1"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "light"
    lang = "zh"
    loading = "lazy"

## Social Accounts
[params.social]
    github = "jim091418"
    instagram = "jim940037"
    # linkedin = "<username>"
    # twitter = "<username>"
    #facebook = "<username>"
    #stackoverflow = "<username>"
    #telegram = "<username>"
    # orcid = "<xxxx-xxxx-xxxx-xxxx>"
    email = "jim091418@gamil.com"
    # mastodon = "<username>"
    # threads = "@<username>"
    # gravatar = "your-email@example.com"
    # pgpkey = "<path-to-your-key-in-/static>"

## Main Menu
[[menu.main]]
    name = "測試工具"
    weight = 300
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Try Hack Me Write up"
    identifier = "thms"
    weight = 200
    url = "/thm/"
[[menu.main]]
    name = "滲透測試"
    identifier = "taccst"
    weight = 250
    url = "/taccst/"
[[menu.main]]
    name = "關於我"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "測試東西"
    identifier = "test"
    weight = 350
    url = "/test/"
